name: Java Build with Gradle

on: 
  push:
    branches: ["main"]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make gradlew executable
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Create jlink image
      run: ./gradlew jlink

    - name: Zip custom runtime image
      run: |
        if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
          zip -r custom-runtime.zip build/image
        else
          powershell -Command "Compress-Archive -Path build/image/* -DestinationPath custom-runtime.zip"
        fi

    - name: Upload custom runtime image
      uses: actions/upload-artifact@v4
      with:
        name: jlink-runtime-${{ matrix.os }}
        path: custom-runtime.zip